name: DevCard

permissions:
  contents: write

on:
  
  schedule:
    - cron: "3 3 1 * *"
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.3.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
