name: Latest tweets
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.tweets.svg
  token: NOT_NEEDED
  base: ""
  plugin_tweets: yes
  plugin_tweets_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  plugin_tweets_user: github
